name: retroquest
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  firebase_core: ^2.32.0
  firebase_auth: ^4.20.0
  cloud_firestore: ^4.17.5
  provider: ^6.1.2
  google_fonts: ^6.2.1
  percent_indicator: ^4.2.3
  fl_chart: ^0.68.0
  firebase_storage: ^11.7.7
  image_picker: ^1.1.2
  responsive_builder: ^0.7.0
  intl: ^0.19.0
  google_sign_in: ^6.2.1
  shared_preferences: ^2.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/RetroQuest.png"

flutter:
  uses-material-design: true

  assets:
    - assets/images/
